name: reaktoro-jupyter

channels:
  - conda-forge

dependencies:
  - reaktoro
  - python
  - numpy
  - jupyter
  - jupyterlab
  - joblib
  - matplotlib
  - ffmpeg
  - pip
  - pip:
    - bokeh
    - pandas
    - matplotlib
    - IPython
    - voila
  - jupytext  # not required in tutorial
  - pytest  # not required in tutorial
